---
title: "hw2"
author: "Matthew Perrotta"
date: "January 30, 2019"
output: pdf_document
---
```{r}
library(tidyverse)
library(deSolve)
```

Problem 1
```{r SIR function}
SIR = function(t, state, parameters){
  with(as.list(c(state, parameters)), {
    dS = -beta*S*I/N;
    dI = beta*S*I/N - gamma*I;
    dR = gamma*I;
    list(c(dS, dI, dR))
  })
}
```

```{r}
#Specify Initial conditions
N = 1e5; # population size
I0 = 10; # initial No. of Infectious people
S0 = N - I0;  # initial No. of Susceptible people
beta=.5; gamma=.3;
parameters=c(beta=beta,gamma=gamma)
times=seq(0,365,by=1);# run for a year
R0 = beta/gamma
state = c(S=S0,I=I0,R=R0)
sim = ode(y=state,times=times,func=SIR,parms=parameters)

s = sim[,'S']/N
i = sim[,'I']/N
r = sim[,'R']/N


View(sim)  # to see what's in the model output 'sim'
```


Problem 2
```{r}
## CHANGE IN NUMBER OF INFECTIOUS
numWk=15; tmstep=7; # weekly increase
wklyS=wklyI=rep(0,numWk+1);
wklyS[1]=S0; wklyI[1]=I0;
wk=1; # first week
times=seq(tmstep*(wk-1),tmstep*wk,by=1);
state=c(S=wklyS[wk],I=wklyI[wk])
sim=ode(y=state,times=times,func=SIR,parms=parameters);
wklyS[wk+1]=tail(sim[,'S'],1); # save new state
wklyI[wk+1]=tail(sim[,'I'],1);
plot(sim[,'time'],sim[,'I'],ylim=c(0,N*.12),xlim=c(0,tmstep*numWk),
     ylab='I',xlab='Time', pch=20)
for (wk in 2:numWk){
  times=seq(tmstep*(wk-1),tmstep*wk,by=1);
  state=c(S=wklyS[wk],I=wklyI[wk])
  sim=ode(y=state,times=times,func=SIR,parms=parameters);
  wklyS[wk+1]=tail(sim[,'S'],1); # save new state
  wklyI[wk+1]=tail(sim[,'I'],1);
  points(tail(sim[,'time'],tmstep),tail(sim[,'I'],tmstep),pch=20)
  readline("Press <return to continue") ## PRESS ENTER TO PROCEED
}

## CHANGE IN THE NUMBER OF SUSCEPTIBLES
wklyS=wklyI=rep(0,numWk+1);
wklyS[1]=S0; wklyI[1]=I0;
wk=1; # first week
times=seq(tmstep*(wk-1),tmstep*wk,by=1);
state=c(S=wklyS[wk],I=wklyI[wk])
sim=ode(y=state,times=times,func=SIR,parms=parameters);
wklyS[wk+1]=tail(sim[,'S'],1); # save new state
wklyI[wk+1]=tail(sim[,'I'],1);
plot(sim[,'time'],sim[,'S']/N,ylim=c(0,1),xlim=c(0,tmstep*numWk),
     ylab='% Susceptible',xlab='Time', pch=20)
for (wk in 2:numWk){
  times=seq(tmstep*(wk-1),tmstep*wk,by=1);
  state=c(S=wklyS[wk],I=wklyI[wk])
  sim=ode(y=state,times=times,func=SIR,parms=parameters);
  wklyS[wk+1]=tail(sim[,'S'],1); # save new state
  wklyI[wk+1]=tail(sim[,'I'],1);
  points(tail(sim[,'time'],tmstep),tail(sim[,'S']/N,tmstep),pch=20)
  readline("Press <return to continue") ## PRESS ENTER TO PROCEED
}

## CHANGE IN THE NUMBER OF RECOVERED
numWk=15; tmstep=7;
wklyS=wklyI=wklyR=rep(0,numWk+1);
wklyS[1]=S0; wklyI[1]=I0; wklyR[1]
wk=1; # first week
times=seq(0,365,by=1);
state=c(S=wklyS[wk],I=wklyI[wk], R=wklyR[wk])
sim=ode(y=state,times=times,func=SIR,parms=parameters);
wklyS[wk+1]=tail(sim[,'S'],1); # save new state
wklyI[wk+1]=tail(sim[,'I'],1);
wklyR[wk+1]=tail(sim[,'R'],1);
plot(sim[,'time'],sim[,'R']/N,ylim=c(0,1),xlim=c(0,tmstep*numWk),
     ylab='% Recovered',xlab='Time', pch=20)
for (wk in 2:numWk){
  times=seq(tmstep*(wk-1),tmstep*wk,by=1);
  state=c(S=wklyS[wk],I=wklyI[wk], R=wklyR[wk])
  sim=ode(y=state,times=times,func=SIR,parms=parameters);
  wklyS[wk+1]=tail(sim[,'S'],1); # save new state
  wklyI[wk+1]=tail(sim[,'I'],1);
  wklyR[wk+1]=tail(sim[,'R'],1);
  points(tail(sim[,'time'],tmstep),tail(sim[,'R']/N,tmstep),pch=20)
  readline("Press <return to continue") ## PRESS ENTER TO PROCEED
}
```

